from . import hr_employee_health
from . import health_patient_mixin
from . import health_vaccine_type
from . import health_visit
from . import health_vaccination
from . import health_checkup
from . import health_profile_mixin
from . import student_health
from . import faculty_health
from . import health_dashboard
