from . import uniform_patron_mixin
from . import product_template_uniform
from . import uniform_stock
from . import uniform_stock_move
from . import uniform_policy
from . import uniform_order
from . import uniform_order_line
from . import student_uniform
from . import faculty_uniform
